import Head from "next/head";
import Image from "next/image";
import { Inter } from "@next/font/google";
import styles from "@/styles/Home.module.css";
import { Button } from "@nextui-org/react/";
import Login from "@/components/login/Login";
import SlideShow from "@/components/SlideShow/SlideShow";
import InfoHome from "@/components/InfoHome/InfoHome";

export default function Home() {
  return (
    <>
      <Head>
        <title>App.Ointment</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <SlideShow />
      <InfoHome />
      <main className={styles.main}></main>
    </>
  );
}
