import Head from "next/head";
import SlideShow from "@/components/SlideShow/SlideShow";
import InfoHome from "@/components/InfoHome/InfoHome";
import Search from "@/components/Search/Search";
import Footer from "@/components/Footer/Footer";

import { AcountActivation } from "@/components/AcountActivation";

export default function Home() {

  return (
    <>
      <Head>
        <title>App.Ointment</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <SlideShow />
      <InfoHome />
      <Search />
      <Footer />
    </>
  );
}
